#try exception
#try คือ การลองทำงานเพื่อหาว่ามีปัญหาเกิดขึ้นหรือไม่
#except คือ การลองทำงานเพื่อหาว่ามีปัญหาเกิดขึ้นหรือไม่
#เราสามารถใช้ try และ except ในการแก้ปัญหาข้อผิดพลาดได้******

#ที่เรานำมายกตัวอย่างคือ การเกิดข้อผิดพลาดในการทำงานของโปรแกรมคำนวณหาผลหารของตัวเลข2จำนวน 

#*********จาก program17.py
#ปัญหาของเราคือ ถ้าเราป้อน ตัวอักษรเข้าไปละ จะเกิดข้อผิดพลาดในการทำงาน
#ปัญหาถัดมา ถ้าป้อนตัวเลขที่2เป็น0 จะเกิดข้อผิดพลาดในการทำงาน

# #code เดิม
# nember1=int(input("ป้อนตัวเลขที่1: "))
# nember2=int(input("ป้อนตัวเลขที่2: "))

# result= nember1/nember2
# print("ผลลัพธ์ = ",result)

#มาแก้ไขปัญหาตรงนี้ด้วย try และ except
try:
    nember1=int(input("ป้อนตัวเลขที่1: "))
    nember2=int(input("ป้อนตัวเลขที่2: "))
    result= nember1/nember2
    print("ผลลัพธ์ = ",result)
except ValueError: #ValueError คือ ปัญหาข้อผิดพลาดเกี่ยวกับตัวอักษร
    print("ข้อมูลไม่ถูกต้อง กรุณาป้อนข้อมูลเฉพาะตัวเลขเท่านั้น")
except ZeroDivisionError: #ZeroDivisionError คือ ปัญหาข้อผิดพลาดเกี่ยวกับตัวเลขที่2เป็น0
    print("ไม่สามารถหารด้วย 0 ได้! เนื่องจากไม่ถูกนิยามในทางคณิตศาสตร์")
    
##หรือ เราใส่ 
#except:
#    print("เกิดข้อผิดพลาดในการทำงาน")
##ก็ได้
    
finally:
    print("--------------------")
    print("สิ้นสุดการทำงาน")
    print("--------------------")